# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  # see https://hub.docker.com/r/coturn/coturn
  # see https://github.com/coturn/coturn/tree/docker/4.5.2-r5/docker/coturn
  coturn:
    build:
      dockerfile: Dockerfile.coturn
    restart: on-failure
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
      - coturn:/var/lib/coturn
volumes:
  coturn:
