# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  coturn:
    build:
      dockerfile: Dockerfile.coturn
    restart: on-failure
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
      - coturn:/var/lib/coturn
volumes:
  coturn:
