# see https://hub.docker.com/r/coturn/coturn
# see https://github.com/coturn/coturn/tree/docker/4.6.2-r3/docker/coturn
FROM coturn/coturn:4.6.2-r3
USER root:root
RUN apt-get update && \
    apt-get install -y sqlite3 && \
    rm -rf /var/lib/apt/lists/*
USER nobody:nogroup
CMD ["--"]
#CMD ["--external-ip=$(detect-external-ip)"]
